> Projeto Desenvolve <br>
Programação Intermediária com Python <br>
Profa. Camila Laranjeira (mila@projetodesenvolve.com.br) <br>

# 3.6 - Pandas

## Exercícios
Antes de continuar, baixe os arquivos das bases de dados de partidas em Copas do Mundo e salve na mesma pasta deste notebook.
* https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/fifa-wc/matches_1930_2022.csv
* https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/fifa-wc/matches_1991_2023.csv

A célula a seguir já carrega os dados em CSV e ajusta as colunas para trabalharmos com os nomes traduzidos (como fizemos em aula).

In [8]:
import pandas as pd
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',12)

wcwomen_df = pd.read_csv('matches_1991_2023.csv')
wcmen_df   = pd.read_csv('matches_1930_2022.csv')
wc = pd.concat((wcwomen_df,wcmen_df)).reset_index()

nomes_traduzidos = {'home_team': 'time_1', 'away_team': 'time_2', 'home_score': 'gols_1', 'away_score': 'gols_2',
                    'Date': 'data', 'Year': 'ano', 'Host': 'país_sede', 'Attendance': 'comparecimento',
                    'Score': 'resultado', 'Round': 'rodada', 'home_goal': 'gols_1_detalhes', 'away_goal': 'gols_2_detalhes',
                    'home_own_goal': 'gols_1_contra', 'away_own_goal': 'gols_2_contra',
                    'home_penalty_goal': 'gols_1_penalti', 'away_penalty_goal': 'gols_2_penalti',
                    'home_red_card': 'cartao_vermelho_1', 'away_red_card': 'cartao_vermelho_2',
                    'home_yellow_card_long': 'cartao_amarelo_1', 'away_yellow_card_long': 'cartao_amarelo_2'}

wc = wc.loc[:, nomes_traduzidos.keys()]
wc.columns = nomes_traduzidos.values()

copa = wc['ano'].apply( lambda x: 'Masculina' if x % 2 == 0 else 'Feminina').astype('string')
wc['copa'] = copa
display(wc)

,time_1,time_2,gols_1,gols_2,data,ano,país_sede,comparecimento,resultado,rodada,gols_1_detalhes,gols_2_detalhes,gols_1_contra,gols_2_contra,gols_1_penalti,gols_2_penalti,cartao_vermelho_1,cartao_vermelho_2,cartao_amarelo_1,cartao_amarelo_2,copa
0,Spain,England,1,0,2023-08-20,2023,"Australia, New Zealand",75784,1–0,Final,Olga Carmona · 29’,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['78’|1:0|Salma Paralluelo'],['55’|1:0|Lauren Hemp'],Feminina
1,Sweden,Australia,2,0,2023-08-19,2023,"Australia, New Zealand",49461,2–0,Third-place match,Kosovare Asllani · 62’,NaN,NaN,NaN,Fridolina Rolfö (P) · 30’,NaN,NaN,NaN,"['88’|2:0|Elin Rubensson', '90+5’|2:0|Lina Hur...",['45+1’|1:0|Katrina Gorry'],Feminina
2,Australia,England,1,3,2023-08-16,2023,"Australia, New Zealand",75784,1–3,Semi-finals,Sam Kerr · 63’,Ella Toone · 36’|Lauren Hemp · 71’|Alessia Rus...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['10’|0:0|Alex Greenwood', '90+5’|1:3|Chloe Ke...",Feminina
3,Spain,Sweden,2,1,2023-08-15,2023,"Australia, New Zealand",43217,2–1,Semi-finals,Salma Paralluelo · 81’|Olga Carmona · 89’,Rebecka Blomqvist · 88’,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Feminina
4,Australia,France,0,0,2023-08-12,2023,"Australia, New Zealand",49461,(7) 0–0 (6),Quarter-finals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['92’|0:0|Katrina Gorry'],NaN,Feminina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,Argentina,France,1,0,1930-07-15,1930,Uruguay,23409,1–0,Group stage,Luis Monti · 81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Masculina
1308,Yugoslavia,Brazil,2,1,1930-07-14,1930,Uruguay,24059,2–1,Group stage,Aleksandar Tirnanić · 21|Ivan Bek · 30,Preguinho · 62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Masculina
1309,Romania,Peru,3,1,1930-07-14,1930,Uruguay,2549,3–1,Group stage,Adalbert Deșu · 1|Constantin Stanciu · 79|Nico...,Luis de Souza Ferreira · 75,NaN,NaN,NaN,NaN,NaN,Plácido Galindo · 70,NaN,NaN,Masculina
1310,United States,Belgium,3,0,1930-07-13,1930,Uruguay,18346,3–0,Group stage,Bart McGhee · 23|Tom Florie · 45|Bert Patenaud...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Masculina
1311,France,Mexico,4,1,1930-07-13,1930,Uruguay,4444,4–1,Group stage,Lucien Laurent · 19|Marcel Langiller · 40|Andr...,Juan Carreño · 70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Masculina

#### Q1.
Faça as conversões de tipo necessárias para que a saída do comando `wc.info()` seja como apresentado a seguir. E **salve o novo dataframe** com o comando `df.to_csv('wc_formatado.csv')`.

```
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   time_1             1312 non-null   string        
 1   time_2             1312 non-null   string        
 2   gols_1             1312 non-null   int64         
 3   gols_2             1312 non-null   int64         
 4   data               1312 non-null   datetime64[ns]
 5   ano                1312 non-null   int64         
 6   país_sede          1312 non-null   string        
 7   comparecimento     1312 non-null   int64         
 8   resultado          1312 non-null   string        
 9   rodada             1312 non-null   category      
 10  gols_1_detalhes    970 non-null    string        
 11  gols_2_detalhes    771 non-null    string        
 12  gols_1_contra      57 non-null     string        
 13  gols_2_contra      30 non-null     string        
 14  gols_1_penalti     170 non-null    string        
 15  gols_2_penalti     119 non-null    string        
 16  cartao_vermelho_1  59 non-null     string        
 17  cartao_vermelho_2  65 non-null     string        
 18  cartao_amarelo_1   834 non-null    string        
 19  cartao_amarelo_2   857 non-null    string        
 20  copa               1312 non-null   string 
```

In [7]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 12)

wcwomen_df = pd.read_csv('matches_1991_2023.csv')
wcmen_df = pd.read_csv('matches_1930_2022.csv')
wc = pd.concat((wcwomen_df, wcmen_df)).reset_index()

nomes_traduzidos = {
    'home_team': 'time_1', 'away_team': 'time_2', 'home_score': 'gols_1', 'away_score': 'gols_2',
    'Date': 'data', 'Year': 'ano', 'Host': 'país_sede', 'Attendance': 'comparecimento',
    'Score': 'resultado', 'Round': 'rodada', 'home_goal': 'gols_1_detalhes', 'away_goal': 'gols_2_detalhes',
    'home_own_goal': 'gols_1_contra', 'away_own_goal': 'gols_2_contra',
    'home_penalty_goal': 'gols_1_penalti', 'away_penalty_goal': 'gols_2_penalti',
    'home_red_card': 'cartao_vermelho_1', 'away_red_card': 'cartao_vermelho_2',
    'home_yellow_card_long': 'cartao_amarelo_1', 'away_yellow_card_long': 'cartao_amarelo_2'
}

wc = wc.loc[:, nomes_traduzidos.keys()]
wc.columns = nomes_traduzidos.values()

copa = wc['ano'].apply(lambda x: 'Masculina' if x % 2 == 0 else 'Feminina').astype('string')
wc['copa'] = copa

# Conversões de tipo
wc['time_1'] = wc['time_1'].astype('string')
wc['time_2'] = wc['time_2'].astype('string')
wc['gols_1'] = wc['gols_1'].astype('int64')
wc['gols_2'] = wc['gols_2'].astype('int64')
wc['data'] = pd.to_datetime(wc['data'])
wc['ano'] = wc['ano'].astype('int64')
wc['país_sede'] = wc['país_sede'].astype('string')
wc['comparecimento'] = wc['comparecimento'].astype('int64')
wc['resultado'] = wc['resultado'].astype('string')
wc['rodada'] = wc['rodada'].astype('category')
wc['gols_1_detalhes'] = wc['gols_1_detalhes'].astype('string')
wc['gols_2_detalhes'] = wc['gols_2_detalhes'].astype('string')
wc['gols_1_contra'] = wc['gols_1_contra'].astype('string')
wc['gols_2_contra'] = wc['gols_2_contra'].astype('string')
wc['gols_1_penalti'] = wc['gols_1_penalti'].astype('string')
wc['gols_2_penalti'] = wc['gols_2_penalti'].astype('string')
wc['cartao_vermelho_1'] = wc['cartao_vermelho_1'].astype('string')
wc['cartao_vermelho_2'] = wc['cartao_vermelho_2'].astype('string')
wc['cartao_amarelo_1'] = wc['cartao_amarelo_1'].astype('string')
wc['cartao_amarelo_2'] = wc['cartao_amarelo_2'].astype('string')
wc['copa'] = wc['copa'].astype('string')

# Salvando o DataFrame formatado
wc.to_csv('wc_formatado.csv', index=False)

# Exibindo informações do DataFrame
wc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1312 entries, 0 to 1311
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   time_1             1312 non-null   string
 1   time_2             1312 non-null   string
 2   gols_1             1312 non-null   int64
 3   gols_2             1312 non-null   int64
 4   data               1312 non-null   datetime64[ns]
 5   ano                1312 non-null   int64
 6   país_sede          1312 non-null   string
 7   comparecimento     1312 non-null   int64
 8   resultado          1312 non-null   string
 9   rodada             1312 non-null   category
 10  gols_1_detalhes    970 non-null    string
 11  gols_2_detalhes    771 non-null    string
 12  gols_1_contra      57 non-null     string
 13  gols_2_contra      30 non-null     string
 14  gols_1_penalti     170 non-null    string
 15  gols_2_penalti     119 non-null    string
 16  cartao_vermelho_1  59 non-null     string
 17  cartao_vermelho_2  65 non-null     string
 18  cartao_amarelo_1   834 non-null    string
 19  cartao_amarelo_2   857 non-null    string
 20  copa               1312 non-null   string
dtypes: category(1), datetime64[ns](1), int64(4), string(15)
memory usage: 206.8 KB

#### Q2.
Apresente a linha do dataframe `wc` que corresponde ao jogo com maior audiência da história.

In [9]:
# Encontrar o jogo com a maior audiência
jogo_maior_audiencia = wc.loc[wc['comparecimento'].idxmax()]

# Exibir a linha correspondente
print(jogo_maior_audiencia)

time_1                  Uruguay
time_2                   Brazil
gols_1                        2
gols_2                        1
data                 1950-07-16
                        ...
cartao_vermelho_1           NaN
cartao_vermelho_2           NaN
cartao_amarelo_1            NaN
cartao_amarelo_2            NaN
copa                  Masculina
Name: 1238, Length: 21, dtype: object

#### Q3.
Aplicando operações sobre as colunas `ano` e `copa` do dataframe `wc`, apresente quantas copas femininas e quantas copas masculinas já aconteceram na história.

Exemplo de saída (valores inventados):
```
Masculina: 22
Feminina: 9
```

In [10]:
# Contar o número de copas masculinas e femininas
contagem_copas = wc.groupby('copa')['ano'].nunique()

# Exibir os resultados
masculina = contagem_copas['Masculina']
feminina = contagem_copas['Feminina']

print(f'Masculina: {masculina}')
print(f'Feminina: {feminina}')

Masculina: 22
Feminina: 9

#### Q3. 
Crie um dataframe `participacao` com as colunas `país`, `copa`, e `num_copas` que armazena a quantidade de copas do mundo que cada país participou, informando se é da copa masculina ou feminina. Ao final imprima, como apresentado a seguir, o top 5 países de cada competição que mais participou de copas do mundo.

Exemplo de saída (valores inventados):
```
país            copa        num_copas
Brazil          Feminina    8
Unites States   Feminina    8
Germany         Feminina    8
Japan           Feminina    7
Colombia        Feminina    7
```

```
país            copa        num_copas
Brazil          Masculina   21
Germany         Masculina   21
Argentina       Masculina   20
England         Masculina   20
Mexico          Masculina   20
```

In [11]:
# Criar um DataFrame com a participação dos países
participacao = wc.groupby(['copa', 'país_sede']).size().reset_index(name='num_copas')

# Exibir o top 5 países de cada competição
top_feminina = participacao[participacao['copa'] == 'Feminina'].nlargest(5, 'num_copas')
top_masculina = participacao[participacao['copa'] == 'Masculina'].nlargest(5, 'num_copas')

print("Top 5 países na Copa Feminina:")
print(top_feminina[['país_sede', 'copa', 'num_copas']])

print("\nTop 5 países na Copa Masculina:")
print(top_masculina[['país_sede', 'copa', 'num_copas']])

Top 5 países na Copa Feminina:
                país_sede      copa  num_copas
0  Australia, New Zealand  Feminina         64
6           United States  Feminina         64
2                China PR  Feminina         58
1                  Canada  Feminina         52
3                  France  Feminina         52

Top 5 países na Copa Masculina:
   país_sede       copa  num_copas
12   Germany  Masculina        102
8     Brazil  Masculina         86
15    Mexico  Masculina         84
11    France  Masculina         82
13     Italy  Masculina         69

#### Q4. 
* Crie um dataframe `gols` com duas colunas `país` e `total_gols` com o total de gols marcados por cada país durante todas as copas do mundo, juntando gols em casa (`gols_1`) e gols como time visitante (`gols_2`).
* Imprima o dataframe `gols` ordenado de forma decrescente, para que os times com mais gols fiquem no topo.

Segue um exemplo ilustrativo com o formato do dataframe resultado:

```
país        total_gols
Brazil      120
Argentina   112
Germany     107
...
```

In [21]:
# Criar o DataFrame com o total de gols por país
gols = wc.groupby('país_sede').agg(total_gols=('gols_1', 'sum', 'gols_2', 'sum'))()

# Calcular o total de gols somando os gols em casa e os gols como visitante
gols['total_gols'] = gols['gols_1'] + gols['gols_2']

# Manter apenas as colunas necessárias
gols = gols[['país_sede', 'total_gols']]

# Renomear a coluna 'país_sede' para 'país'
gols.rename(columns={'país_sede': 'país'}, inplace=True)

# Ordenar o DataFrame de forma decrescente
gols = gols.sort_values(by='total_gols', ascending=False)

# Exibir o DataFrame
print(gols)

TypeError: Must provide 'func' or tuples of '(column, aggfunc).

#### Q5. 
Qual país tomou mais cartões amarelos somando todas as copas?

Neste exercício você vai trabalhar com as colunas `cartao_amarelo_1` e `cartao_amarelo_2` onde cada observação é uma string represetando uma lista dos cartões amarelos de um único jogo na forma `minuto|placar|jogador(a)`. Por exemplo:
```
['16’|1:0|Rosana Gómez', '20’|2:0|Gabriela Chávez]
```

Recomendo criar colunas `num_cartoes_1` e `num_cartoes_2` a partir de cada coluna `cartao_amarelo_X` usando o método genérico `apply` para chamar uma função que você vai criar para transformar uma observação de cartão amarelo em uma contagem de elementos da lista. 

Lembre de levar em consideração que muitas observações são `NaN`. 

Em seguida faça sua mágica para agrupar as informações por país, acumular os cartões de jogos em casa e jogos visitante, e produzir o resultado final como apresentado a seguir (valores inventados):

```
país        cartões amarelos
Argentina   97
England     93
Australia   93
...
```

In [22]:
import pandas as pd
import numpy as np

# Função para contar cartões amarelos em uma lista de strings
def contar_cartoes(cartoes):
    if pd.isna(cartoes):  # Verifica se a observação é NaN
        return 0
    return len(eval(cartoes))  # Usa eval para converter a string em uma lista e conta os elementos

# Criar novas colunas com o número de cartões amarelos
wc['num_cartoes_1'] = wc['cartao_amarelo_1'].apply(contar_cartoes)
wc['num_cartoes_2'] = wc['cartao_amarelo_2'].apply(contar_cartoes)

# Agrupar por país e somar os cartões amarelos
cartoes_por_pais = wc.groupby('país_sede').agg(cartões_amarelos=('num_cartoes_1', 'sum') + ('num_cartoes_2', 'sum')).reset_index()

# Ordenar o DataFrame de forma decrescente
cartoes_por_pais = cartoes_por_pais.sort_values(by='cartões_amarelos', ascending=False)

# Exibir o DataFrame
print(cartoes_por_pais)

TypeError: Must provide 'func' or tuples of '(column, aggfunc).

#### Q6.
Qual o top10 jogadores com mais gols em copa? Considere gols em jogo e gols de pênalti.

Para conseguir essa informação, você precisará trabalhar com as colunas:
```
10  gols_1_detalhes         
11  gols_2_detalhes    
14  gols_1_penalti     
15  gols_2_penalti     
```

Essas também são colunas textuais, onde cada observações apresenta todos os gols de uma partida separados pelo caracter `|`. Cada gol está na forma `'Jogador(a) · minuto’'`. Por exemplo:
```
'Alex Morgan · 12’|Rose Lavelle · 20’'
```

Lembre de levar em consideração que muitas observações são `NaN`. 

Recomendo criar um dicionário à parte, onde cada chave será um jogador encontrado nessas colunas do dataframe `wc` e o valor correspondente será a contagem de ocorrências desses nomes.

Em seguida basta converter o seu dicionário em um dataframe e imprimí-lo na forma (valores não são inventados 😁):
```
jogador(a)      num_gols 
Marta           17
Miroslav Klose  16
... 
```

In [23]:
import pandas as pd
import numpy as np
from collections import defaultdict

# Dicionário para contar os gols dos jogadores
gols_jogadores = defaultdict(int)

# Função para contar gols de uma coluna
def contar_gols(coluna):
    if pd.isna(coluna):  # Verifica se a observação é NaN
        return
    for gol in coluna.split('|'):
        jogador = gol.split(' · ')[0]  # Extrai o nome do jogador
        gols_jogadores[jogador] += 1  # Incrementa a contagem de gols

# Aplicar a função para as colunas de gols
wc['gols_1_detalhes'].apply(contar_gols)
wc['gols_2_detalhes'].apply(contar_gols)

# Contar gols de pênalti
wc['gols_1_penalti'].apply(lambda x: contar_gols(x) if pd.notna(x) else None)
wc['gols_2_penalti'].apply(lambda x: contar_gols(x) if pd.notna(x) else None)

# Converter o dicionário em DataFrame
gols_df = pd.DataFrame(gols_jogadores.items(), columns=['jogador(a)', 'num_gols'])

# Obter o top 10 jogadores com mais gols
top10_jogadores = gols_df.nlargest(10, 'num_gols')

# Exibir o DataFrame
print(top10_jogadores)

            jogador(a)  num_gols
433     Miroslav Klose        16
169       Birgit Prinz        14
497            Ronaldo        14
894        Gerd Müller        13
974      Just Fontaine        13
174       Abby Wambach        12
882               Pelé        12
603   Jürgen Klinsmann        11
1019     Sándor Kocsis        11
98           Cristiane        10